export const INITIAL_PENALTY_INTERVAL_QTY = 10;
export const INITIAL_PENALTY_INTERVAL_UNIT = "minutes";
export const INITIAL_PENALTY_INTERVAL = `${INITIAL_PENALTY_INTERVAL_QTY} ${INITIAL_PENALTY_INTERVAL_UNIT}`;
