name: Require Changeset on CLI

on:
  # Trigger the workflow every time you push to the `trunk` branch
  pull_request:
    branches: [trunk]
    paths:
      # only run on change to packages/cli
      - "packages/cli/**"
        # exclude files auto-updated by a Versions PR to prevent this workflow from running there
      - "!packages/cli/package.json"
      - "!packages/cli/CHANGELOG.md"
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

permissions:
  contents: read

jobs:
  require-changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          # fetch all history for all branches and tags.
          # changesets won't be able to find 'origin/trunk' without this
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          check-latest: true
          cache: "pnpm"

      - name: Check for changeset
        run: pnpm dlx @changesets/cli status --since=origin/trunk
